Inspired by https://www.reddit.com/r/baseball/comments/jzo3gi/was_the_springfield_nuclear_power_plant_company/

> Not including Homer (since his WAR is yet to be calculated by my knowledge), the average player on the softball team for the Springfield Nuclear Power Plant had a career bWAR of 63.3

    SS - Ozzie Smith (76.9)
    CF - Ken Griffey Jr. (83.8)
    3B - Wade Boggs (91.4)
    LF - Jose Canseco (42.4)
    RF - Darryl Strawberry (42.2)
    1B - Don Mattingly (42.4)
    C - Mike Scioscia (26.1)
    2B - Steve Sax (25.7)
    P - Roger Clemens (139.2)

> So I ask, was the Springfield Nuclear Power Plant company softball team the greatest team of all time?

In [1]:
import pandas as pd

In [2]:
wars = pd.read_parquet('../data/mine/WAR_tot_seasonal.parquet')
career_wars = wars.groupby('bbref_id')['WAR_total'].sum()
career_wars.sort_values()

bbref_id
leveyji01     -7.5
flynndo01     -6.9
meyerda01     -6.5
harrivi01     -6.3
staintu01     -6.2
             ...
cobbty01     151.2
mayswi01     156.3
bondsba01    162.8
johnswa01    164.5
ruthba01     182.4
Name: WAR_total, Length: 17750, dtype: float64

In [3]:
# Now merge in retro_id

ppl = pd.read_parquet('../data/bd/people.parquet')
ppl.columns

Index(['player_id', 'birth_year', 'birth_month', 'birth_day', 'birth_country',
       'birth_state', 'birth_city', 'death_year', 'death_month', 'death_day',
       'death_country', 'death_state', 'death_city', 'name_first', 'name_last',
       'name_given', 'weight', 'height', 'bats', 'throws', 'debut',
       'final_game', 'retro_id', 'bbref_id'],
      dtype='object')

In [4]:
war_lookup = pd.merge(left=ppl[['retro_id', 'bbref_id']], right=career_wars, on='bbref_id')
war_lookup

       retro_id   bbref_id  WAR_total
0      aardd001  aardsda01        1.9
1      aaroh101  aaronha01      143.2
2      aarot101  aaronto01       -2.8
3      aased001   aasedo01       15.1
4      abada001   abadan01       -0.3
...         ...        ...        ...
17536  zupof101   zupofr01       -0.1
17537  zuvep001  zuvelpa01       -2.4
17538  zuveg101  zuverge01        6.9
17539  zwild101  zwilldu01        8.5
17540  zycht001   zychto01        1.6

[17541 rows x 3 columns]

In [5]:
# Now get starting lineups

gls = pd.read_parquet('../data/mine/gl_starters.parquet')
gls.columns

Index(['player_id', 'game_id', 'date', 'yr', 'game_type', 'team', 'HA', 'pos',
       'batting_pos'],
      dtype='object')

In [15]:
gls_war = pd.merge(left=gls, right=war_lookup, left_on='player_id', right_on='retro_id')
lineups = gls_war.groupby(['game_id', 'team', 'game_type'])['WAR_total'].agg([sum, len]).sort_values(by='sum', ascending=False).reset_index().set_index(['game_id', 'team'])
lineups.tail(30)

                  game_type   sum  len
game_id      team
BUF191407160 BUF         RS  -1.7  9.0
BSN190209102 SLN         RS  -2.0  8.0
NYA195108040 SLA         RS  -2.1  9.0
WS1195406110 BAL         RS  -2.2  9.0
CIN201209090 HOU         RS  -2.7  9.0
SLA195009200 SLA         RS  -2.9  9.0
TEX197209020 TEX         RS  -3.4  9.0
SLA195104292 SLA         RS  -3.5  9.0
NYA195005112 SLA         RS  -3.6  9.0
PHI193909282 PHI         RS  -4.0  9.0
CLE195108310 SLA         RS  -4.1  9.0
SLA195108170 SLA         RS  -4.1  9.0
SLA195108261 SLA         RS  -4.1  9.0
SLA195109060 SLA         RS  -4.1  9.0
DET195108120 SLA         RS  -4.1  9.0
WS1195406120 BAL         RS  -4.2  9.0
WS1195107270 SLA         RS  -4.3  9.0
SLA195108210 SLA         RS  -4.7  9.0
BOS195106172 SLA         RS  -5.3  9.0
SDN199310030 SDN         RS  -5.3  9.0
BUF191509061 BLF         RS  -5.6  9.0
CLE195108070 SLA         RS  -6.1  9.0
PHA195106220 SLA         RS  -7.4  9.0
CHA195104252 SLA         RS  -7.9  9.0
BSN194409162 BRO         RS  -9.0  9.0
NEW191510032 BLF         RS  -9.6  9.0
CHA198209272 SEA         RS -10.0  9.0
DET195104230 SLA         RS -10.3  9.0
PHA194806131 SLA         RS -10.4  9.0
PTF191509182 BLF         RS -11.5  9.0

In [17]:
lineups[lineups['game_type']=='RS'].head(50)

                  game_type    sum  len
game_id      team
SLA192806070 PHA         RS  641.5  9.0
PHA193304270 NYA         RS  636.2  9.0
DET193306280 NYA         RS  634.1  9.0
NYA193307220 NYA         RS  634.1  9.0
DET193305020 NYA         RS  634.1  9.0
NYA193308072 NYA         RS  633.7  9.0
WS1193307270 NYA         RS  633.7  9.0
CHA193306181 NYA         RS  633.7  9.0
DET193206070 NYA         RS  633.7  9.0
CHA193308190 NYA         RS  633.7  9.0
SLA193208071 NYA         RS  633.7  9.0
NYA193208191 NYA         RS  633.7  9.0
NYA193305260 NYA         RS  633.7  9.0
NYA193305200 NYA         RS  633.7  9.0
CLE193305072 NYA         RS  633.7  9.0
NYA193304140 NYA         RS  633.7  9.0
NYA193308020 NYA         RS  633.7  9.0
WS1193305311 NYA         RS  633.7  9.0
PHA193308121 NYA         RS  633.7  9.0
WS1193208130 NYA         RS  633.7  9.0
SLA193305141 NYA         RS  633.7  9.0
BOS193304210 NYA         RS  633.7  9.0
PHA193209210 NYA         RS  633.7  9.0
CHA193206160 NYA         RS  629.5  9.0
NYA193208292 NYA         RS  629.5  9.0
NYA193208240 NYA         RS  629.5  9.0
PHA193108280 NYA         RS  629.5  9.0
CLE193206120 NYA         RS  629.5  9.0
NYA193206260 NYA         RS  629.5  9.0
PHA193206011 NYA         RS  629.5  9.0
SLA193206210 NYA         RS  629.5  9.0
SLA193106200 NYA         RS  629.5  9.0
CLE193108141 NYA         RS  629.5  9.0
CHA193108231 NYA         RS  629.5  9.0
NYA193108080 NYA         RS  629.5  9.0
NYA193109210 NYA         RS  629.5  9.0
NYA193109262 NYA         RS  629.5  9.0
NYA193306061 NYA         RS  610.6  9.0
DET193206100 NYA         RS  610.6  9.0
SLA193208100 NYA         RS  610.6  9.0
CHA192707130 PHA         RS  609.7  9.0
NYA193307150 NYA         RS  608.8  9.0
NYA193307070 NYA         RS  608.8  9.0
SLA193306231 NYA         RS  606.8  9.0
SLA193206220 NYA         RS  606.4  9.0
NYA193205301 NYA         RS  606.4  9.0
BOS193108051 NYA         RS  606.4  9.0
NYA193109250 NYA         RS  606.4  9.0
SLA193106220 NYA         RS  606.4  9.0
CHA193206150 NYA         RS  606.4  9.0

In [31]:
import numpy as np
lineups.reset_index().groupby('team').first().sort_values(by='sum', ascending=False)

           game_id game_type    sum  len
team
ALS   NLS193407100       ASG  750.0  9.0
NLS   NLS200407130       ASG  731.5  9.0
PHA   SLA192806070        RS  641.5  9.0
NYA   PHA193304270        RS  636.2  9.0
WS1   WS1192705301        RS  545.6  9.0
CIN   LAN197709150        RS  534.0  9.0
MLN   CIN196405190        RS  532.6  9.0
PHI   CIN198305100        RS  521.7  9.0
BOS   BOS191509200        RS  514.6  9.0
HOU   HOU200408030        RS  505.5  9.0
SFN   MLN196407160        RS  499.3  9.0
SEA   ANA200009290        RS  485.6  9.0
BAL   NYA197109220        RS  474.2  9.0
CLE   CLE199505290        RS  473.9  9.0
SLN   ARI200507060        RS  465.7  9.0
NY1   NY1192708211        RS  463.2  9.0
ATL   ATL196607260        RS  456.1  9.0
DET   DET191609190        RS  455.0  9.0
TOR   PHI199310210        PS  452.6  9.0
CAL   CAL198204140        RS  449.3  9.0
OAK   BOS199009030        RS  440.5  9.0
CHN   SDN198807100        RS  440.5  9.0
BRO   PIT194207200        RS  439.8  9.0
NYN   PHI197205210        RS  437.0  9.0
CHA   CHA199109010        RS  424.6  9.0
LAN   SFN200608190        RS  422.8  9.0
MIL   MIL198109150        RS  406.3  9.0
PIT   PIT196905301        RS  400.7  9.0
ARI   SLN200104180        RS  399.1  9.0
TEX   TEX200105310        RS  394.6  9.0
MIN   NYA196905240        RS  384.0  9.0
MON   ATL198305090        RS  381.1  9.0
SDN   SDN199005020        RS  369.7  9.0
BSN   BSN194804280        RS  367.4  9.0
KCA   MIL197505310        RS  365.1  9.0
ANA   ANA199708270        RS  358.3  9.0
FLO   COL199704230        RS  350.2  9.0
SLA   PHA193705240        RS  290.1  9.0
COL   FLO199508080        RS  279.3  9.0
KC1   KC1196709220        RS  273.1  9.0
TBA   TBA201104010        RS  272.0  9.0
WAS   NYN201704230        RS  266.5  9.0
MIA   MIA201505180        RS  237.0  9.0
WS2   WS2197104090        RS  196.5  9.0
LAA   WS2196408142        RS  183.6  9.0
BLA   PHA190207020        RS  170.0  8.0
CHF   KCF191506110        RS  163.6  9.0
SLF   SLF191508011        RS  158.1  9.0
IND   CHF191407121        RS  157.2  9.0
NEW   NEW191505060        RS  131.3  9.0
BRF   BRF191410020        RS  119.7  9.0
SE1   CAL196904080        RS  115.9  9.0
BLF   BLF191409281        RS  108.1  9.0
BUF   BUF191508160        RS  104.9  9.0
PTF   PTF191504200        RS  103.8  9.0
KCF   BUF191506210        RS   77.8  9.0
MLA   MLA190107100        RS   74.8  9.0
MID   PH1187208030        RS   -0.1  1.0
BS1   NY2187405140        RS   -0.1  1.0

In [33]:
lineups[lineups['game_type']=='RS'].groupby('game_id')['sum'].sum().sort_values(ascending=False).head(20)

game_id
PHA193308121    1045.9
PHA192805280    1029.2
PHA192805260    1006.4
NYA192704120    1000.1
PHA192804110     997.9
PHA192704200     997.4
PHA192806270     986.1
PHA192705301     982.6
NYA193308030     977.6
NYA193206260     977.5
PHA192705311     974.0
PHA193209210     967.6
PHA192805251     966.4
WS1192604200     966.2
SFN196404140     964.2
NYA193308072     963.7
WS1193307270     963.7
NYA193204200     962.1
NYA192806210     961.8
SFN196408161     959.8
Name: sum, dtype: float64

In [ ]:
lineups[(lineups['game_type']=='RS')& (lineups[lineups['game_type']=='RS'])]