In [1]:
import boxball_loader as bbl
import baseball_stats_utils as utils
import webbrowser # to open boxscores of matching games

In [2]:
glt = bbl.load_gamelog_teams(game_types=bbl.GameType.ALL, years=range(1969, 2021))
sdp = glt[glt['team']=='SDN']
sdp

,game_id,date,double_header,yr,game_type,park_id,team,team_league,team_game_number,runs_scored,...,batting_8_position,batting_9_player_id,batting_9_name,batting_9_position,HA,opp,runs_allowed,W,L,linescore_parsed
70061,SDN196904080,1969-04-08,0,1969,RS,SAN01,SDN,NL,1,2,...,2.0,selmd101,Dick Selma,1.0,H,HOU,1,True,False,"[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, nan]"
70071,SDN196904090,1969-04-09,0,1969,RS,SAN01,SDN,NL,2,2,...,2.0,podrj101,Johnny Podres,1.0,H,HOU,0,True,False,"[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan]"
70078,SDN196904100,1969-04-10,0,1969,RS,SAN01,SDN,NL,3,2,...,2.0,kelld102,Dick Kelley,1.0,H,HOU,0,True,False,"[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, nan]"
70091,SDN196904110,1969-04-11,0,1969,RS,SAN01,SDN,NL,4,0,...,2.0,kirbc101,Clay Kirby,1.0,H,SFN,8,False,True,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
70103,SDN196904120,1969-04-12,0,1969,RS,SAN01,SDN,NL,5,1,...,2.0,mcbea101,Al McBean,1.0,H,SFN,5,False,True,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95853,SDN202010010,2020-10-01,0,2020,PS,SAN02,SDN,NL,2,11,...,2.0,cronj001,Jake Cronenworth,4.0,H,SLN,9,True,False,"[0.0, 0.0, 0.0, 2.0, 0.0, 4.0, 3.0, 2.0, nan]"
95856,SDN202010020,2020-10-02,0,2020,PS,SAN02,SDN,NL,3,4,...,2.0,cronj001,Jake Cronenworth,4.0,H,SLN,0,True,False,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2.0, 1.0, nan]"
123287,LAN202010060,2020-10-06,0,2020,PS,LOS03,SDN,NL,1,1,...,2.0,profj001,Jurickson Profar,7.0,A,LAN,5,False,True,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
123291,LAN202010070,2020-10-07,0,2020,PS,LOS03,SDN,NL,2,5,...,2.0,grist001,Trent Grisham,8.0,A,LAN,6,False,True,"[0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 2.0]"
123295,SDN202010080,2020-10-08,0,2020,PS,SAN02,SDN,NL,3,3,...,4.0,castj006,Jason Castro,2.0,H,LAN,12,False,True,"[0.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"

In [3]:
sdp.bb.max()

14.0

In [4]:
most = sdp.query('bb >= 12 and po <= 27')
most

,game_id,date,double_header,yr,game_type,park_id,team,team_league,team_game_number,runs_scored,...,batting_8_position,batting_9_player_id,batting_9_name,batting_9_position,HA,opp,runs_allowed,W,L,linescore_parsed
18428,SDN197808100,1978-08-10,0,1978,RS,SAN01,SDN,NL,115,15,...,4.0,joner101,Randy Jones,1.0,H,CIN,3,True,False,"[3.0, 0.0, 1.0, 0.0, 1.0, 3.0, 6.0, 1.0, nan]"
165391,SDN198009090,1980-09-09,0,1980,RS,SAN01,SDN,NL,140,12,...,4.0,muras001,Steve Mura,1.0,H,SFN,5,True,False,"[4.0, 2.0, 1.0, 1.0, 0.0, 1.0, 3.0, 0.0, nan]"
10489,SDN200005310,2000-05-31,0,2000,RS,SAN01,SDN,NL,52,9,...,6.0,loper001,Rodrigo Lopez,1.0,H,MIL,5,True,False,"[0.0, 1.0, 0.0, 0.0, 4.0, 0.0, 4.0, 0.0, nan]"
166450,SFN201005110,2010-05-11,0,2010,RS,SFO03,SDN,NL,32,3,...,6.0,leblw001,Wade LeBlanc,1.0,A,SFN,2,True,False,"[0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"

In [5]:
most.game_id.apply(utils.create_bbref_boxscore_url).values

array(['https://www.baseball-reference.com/boxes/SDN/SDN197808100.shtml',
       'https://www.baseball-reference.com/boxes/SDN/SDN198009090.shtml',
       'https://www.baseball-reference.com/boxes/SDN/SDN200005310.shtml',
       'https://www.baseball-reference.com/boxes/SFN/SFN201005110.shtml'],
      dtype=object)

In [6]:
print(most[['date', 'park_id', 'team', 'opp', 'bb']].to_markdown())

|        | date                | park_id   | team   | opp   |   bb |
|-------:|:--------------------|:----------|:-------|:------|-----:|
|  18428 | 1978-08-10 00:00:00 | SAN01     | SDN    | CIN   |   12 |
| 165391 | 1980-09-09 00:00:00 | SAN01     | SDN    | SFN   |   12 |
|  10489 | 2000-05-31 00:00:00 | SAN01     | SDN    | MIL   |   12 |
| 166450 | 2010-05-11 00:00:00 | SFO03     | SDN    | SFN   |   12 |

In [7]:
print(most[['date', 'park_id', 'team', 'opp', 'bb']].to_string())

             date park_id team  opp    bb
18428  1978-08-10   SAN01  SDN  CIN  12.0
165391 1980-09-09   SAN01  SDN  SFN  12.0
10489  2000-05-31   SAN01  SDN  MIL  12.0
166450 2010-05-11   SFO03  SDN  SFN  12.0

In [9]:
[webbrowser.open(utils.create_bbref_boxscore_url(game_id)) for game_id in most['game_id']]

[True, True, True, True]