In [1]:
import pandas as pd
import boxball_loader as bbl
import baseball_stats_utils as bsu

In [2]:
careers = bbl.load_batting(coalesce_type=bbl.CoalesceMode.PLAYER_CAREER)
careers

,g,ab,r,h,_2b,_3b,hr,rbi,sb,cs,bb,so,ibb,hbp,sh,sf,gidp
player_id,,,,,,,,,,,,,,,,,
aardsda01,331,4,0,0,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
aaronha01,3298,12364,2174,3771,624,98,755,2297.0,240.0,73.0,1402,1383.0,293.0,32.0,21.0,121.0,328.0
aaronto01,437,944,102,216,42,6,13,94.0,9.0,8.0,86,145.0,3.0,0.0,9.0,6.0,36.0
aasedo01,448,5,0,0,0,0,0,0.0,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0
abadan01,15,21,1,2,0,0,0,0.0,0.0,1.0,4,5.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zupofr01,16,18,3,3,1,0,0,0.0,0.0,0.0,2,6.0,0.0,0.0,0.0,0.0,0.0
zuvelpa01,209,491,41,109,17,2,2,20.0,2.0,0.0,34,50.0,1.0,2.0,18.0,0.0,8.0
zuverge01,266,142,5,21,2,1,0,7.0,0.0,1.0,9,39.0,0.0,0.0,16.0,0.0,3.0
zwilldu01,366,1280,167,364,76,15,30,202.0,46.0,0.0,128,155.0,0.0,4.0,31.0,0.0,0.0
zychto01,70,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
ppl = bbl.load_people()
ppl.columns

Index(['player_id', 'birth_year', 'birth_month', 'birth_day', 'birth_country',
       'birth_state', 'birth_city', 'death_year', 'death_month', 'death_day',
       'death_country', 'death_state', 'death_city', 'name_first', 'name_last',
       'name_given', 'weight', 'height', 'bats', 'throws', 'debut',
       'final_game', 'retro_id', 'bbref_id'],
      dtype='object')

In [4]:
career_hr = pd.merge(left=careers[['hr']], right=ppl[['retro_id', 'player_id']], right_on='player_id', left_index=True).set_index('retro_id')['hr']
career_hr

retro_id
aardd001      0
aaroh101    755
aarot101     13
aased001      0
abada001      0
           ...
zupof101      0
zuvep001      2
zuveg101      0
zwild101     30
zycht001      0
Name: hr, Length: 19898, dtype: int16

In [5]:
gls = bbl.load_gamelog_starters(bbl.GameType.ALL)
gls.columns

Index(['player_id', 'game_id', 'date', 'yr', 'game_type', 'team', 'HA', 'pos',
       'batting_pos'],
      dtype='object')

In [6]:
gls_hr = pd.merge(left=gls, right=career_hr, right_index=True, left_on='player_id')

In [7]:
lineup_hrs = gls_hr.groupby(['game_id', 'team', 'yr'])['hr'].sum().sort_values()
lineup_hrs

game_id       team  yr
BR1187205090  BR1   1872       0
BR1187205070  BR1   1872       0
BR1187205180  BR1   1872       0
WS4187205170  WS3   1872       2
WS3187204180  WS3   1872       2
                            ...
ALS199907130  NLS   1999    3537
ALS200307150  NLS   2003    3539
NLS200407130  NLS   2004    3659
ALS199907130  ALS   1999    3677
ALS200107100  NLS   2001    3935
Name: hr, Length: 405904, dtype: int16

In [8]:
lineup_hrs.tail(50)

game_id       team  yr
MIN200604160  NYA   2006    3211
ANA200604070  NYA   2006    3211
OAK200604050  NYA   2006    3211
OAK200604040  NYA   2006    3211
OAK200604030  NYA   2006    3211
MIN200604140  NYA   2006    3211
TEX200605050  NYA   2006    3211
NYA200604270  NYA   2006    3211
NYA200604290  NYA   2006    3211
NYA200609290  NYA   2006    3212
NYA200610050  NYA   2006    3212
NYA200610030  NYA   2006    3212
NYA200609270  NYA   2006    3212
NYA201206080  NYA   2012    3218
NYA201205020  NYA   2012    3233
NLS200407130  ALS   2004    3241
NYA200506250  NYA   2005    3282
NYA200506150  NYA   2005    3282
BAL200509290  NYA   2005    3282
BAL200509280  NYA   2005    3282
OAK200509020  NYA   2005    3282
BOS200509300  NYA   2005    3282
NYA200506230  NYA   2005    3282
TOR200509170  NYA   2005    3282
KCA200506010  NYA   2005    3282
TOR200509180  NYA   2005    3282
TBA200509140  NYA   2005    3282
TEX200507180  NYA   2005    3282
NLS200207090  NLS   2002    3291
CLE200508030  NYA   2005    3315
ANA200507240  NYA   2005    3315
NYA200505250  NYA   2005    3315
DET200507010  NYA   2005    3315
ANA200510050  NYA   2005    3315
BOS200507170  NYA   2005    3315
TBA200508170  NYA   2005    3315
NYA200507270  NYA   2005    3315
CHA200508190  NYA   2005    3315
CHA200508200  NYA   2005    3315
NYA200508230  NYA   2005    3315
ALS200507120  NLS   2005    3334
ALS200107100  ALS   2001    3360
ALS199707080  ALS   1997    3417
NLS199807070  ALS   1998    3454
ALS200507120  ALS   2005    3482
ALS199907130  NLS   1999    3537
ALS200307150  NLS   2003    3539
NLS200407130  NLS   2004    3659
ALS199907130  ALS   1999    3677
ALS200107100  NLS   2001    3935
Name: hr, dtype: int16

In [9]:
lineup_hrs.reset_index().groupby(['team', 'yr', 'hr'])['game_id'].count().reset_index().sort_values(by='hr').tail(50)

       team    yr    hr  game_id
55      ALS  1985  3016        1
129291  NYA  2005  3017       10
117954  NLS  1995  3028        1
129292  NYA  2005  3031        2
129293  NYA  2005  3032        2
129876  NYA  2012  3042        1
129792  NYA  2011  3042        4
129877  NYA  2012  3044       21
117956  NLS  1997  3046        1
129294  NYA  2005  3056        1
117914  NLS  1959  3056        1
129728  NYA  2010  3058        9
129295  NYA  2005  3064       16
73      ALS  2003  3064        1
129793  NYA  2011  3072        2
117957  NLS  1998  3079        1
117930  NLS  1971  3081        1
82      ALS  2012  3086        1
129296  NYA  2005  3087        3
129878  NYA  2012  3090        1
129297  NYA  2005  3114        4
129298  NYA  2005  3120       10
129299  NYA  2005  3133        1
129300  NYA  2005  3139        2
117913  NLS  1958  3143        1
129301  NYA  2005  3181        1
129794  NYA  2011  3188        5
117924  NLS  1965  3189        1
117915  NLS  1959  3190        1
117931  NLS  1972  3191        1
117916  NLS  1960  3197        1
117917  NLS  1960  3206        1
129403  NYA  2006  3211       10
129404  NYA  2006  3212        4
129879  NYA  2012  3218        1
129880  NYA  2012  3233        1
74      ALS  2004  3241        1
129302  NYA  2005  3282       12
117961  NLS  2002  3291        1
129303  NYA  2005  3315       11
117964  NLS  2005  3334        1
71      ALS  2001  3360        1
67      ALS  1997  3417        1
68      ALS  1998  3454        1
75      ALS  2005  3482        1
117958  NLS  1999  3537        1
117962  NLS  2003  3539        1
117963  NLS  2004  3659        1
69      ALS  1999  3677        1
117960  NLS  2001  3935        1

In [10]:
lineup_hrs.loc[lineup_hrs>3000].reset_index().groupby(['team'])['game_id'].count()

team
ALS      9
NLS     17
NYA    148
Name: game_id, dtype: int64

In [11]:
top_hr = lineup_hrs.tail(50).reset_index()
top_hr['url'] = top_hr['game_id'].apply(lambda g: bsu.create_bbref_boxscore_url(g))
top_hr

,game_id,team,yr,hr,url
0,MIN200604160,NYA,2006,3211,https://www.baseball-reference.com/boxes/MIN/M...
1,ANA200604070,NYA,2006,3211,https://www.baseball-reference.com/boxes/ANA/A...
2,OAK200604050,NYA,2006,3211,https://www.baseball-reference.com/boxes/OAK/O...
3,OAK200604040,NYA,2006,3211,https://www.baseball-reference.com/boxes/OAK/O...
4,OAK200604030,NYA,2006,3211,https://www.baseball-reference.com/boxes/OAK/O...
5,MIN200604140,NYA,2006,3211,https://www.baseball-reference.com/boxes/MIN/M...
6,TEX200605050,NYA,2006,3211,https://www.baseball-reference.com/boxes/TEX/T...
7,NYA200604270,NYA,2006,3211,https://www.baseball-reference.com/boxes/NYA/N...
8,NYA200604290,NYA,2006,3211,https://www.baseball-reference.com/boxes/NYA/N...
9,NYA200609290,NYA,2006,3212,https://www.baseball-reference.com/boxes/NYA/N...
10,NYA200610050,NYA,2006,3212,https://www.baseball-reference.com/boxes/NYA/N...
11,NYA200610030,NYA,2006,3212,https://www.baseball-reference.com/boxes/NYA/N...
12,NYA200609270,NYA,2006,3212,https://www.baseball-reference.com/boxes/NYA/N...
13,NYA201206080,NYA,2012,3218,https://www.baseball-reference.com/boxes/NYA/N...
14,NYA201205020,NYA,2012,3233,https://www.baseball-reference.com/boxes/NYA/N...
15,NLS200407130,ALS,2004,3241,https://www.baseball-reference.com/boxes/NLS/N...
16,NYA200506250,NYA,2005,3282,https://www.baseball-reference.com/boxes/NYA/N...
17,NYA200506150,NYA,2005,3282,https://www.baseball-reference.com/boxes/NYA/N...
18,BAL200509290,NYA,2005,3282,https://www.baseball-reference.com/boxes/BAL/B...
19,BAL200509280,NYA,2005,3282,https://www.baseball-reference.com/boxes/BAL/B...
20,OAK200509020,NYA,2005,3282,https://www.baseball-reference.com/boxes/OAK/O...
21,BOS200509300,NYA,2005,3282,https://www.baseball-reference.com/boxes/BOS/B...
22,NYA200506230,NYA,2005,3282,https://www.baseball-reference.com/boxes/NYA/N...
23,TOR200509170,NYA,2005,3282,https://www.baseball-reference.com/boxes/TOR/T...
24,KCA200506010,NYA,2005,3282,https://www.baseball-reference.com/boxes/KCA/K...
25,TOR200509180,NYA,2005,3282,https://www.baseball-reference.com/boxes/TOR/T...
26,TBA200509140,NYA,2005,3282,https://www.baseball-reference.com/boxes/TBA/T...
27,TEX200507180,NYA,2005,3282,https://www.baseball-reference.com/boxes/TEX/T...
28,NLS200207090,NLS,2002,3291,https://www.baseball-reference.com/boxes/NLS/N...
29,CLE200508030,NYA,2005,3315,https://www.baseball-reference.com/boxes/CLE/C...
30,ANA200507240,NYA,2005,3315,https://www.baseball-reference.com/boxes/ANA/A...
31,NYA200505250,NYA,2005,3315,https://www.baseball-reference.com/boxes/NYA/N...
32,DET200507010,NYA,2005,3315,https://www.baseball-reference.com/boxes/DET/D...
33,ANA200510050,NYA,2005,3315,https://www.baseball-reference.com/boxes/ANA/A...
34,BOS200507170,NYA,2005,3315,https://www.baseball-reference.com/boxes/BOS/B...
35,TBA200508170,NYA,2005,3315,https://www.baseball-reference.com/boxes/TBA/T...
36,NYA200507270,NYA,2005,3315,https://www.baseball-reference.com/boxes/NYA/N...
37,CHA200508190,NYA,2005,3315,https://www.baseball-reference.com/boxes/CHA/C...
38,CHA200508200,NYA,2005,3315,https://www.baseball-reference.com/boxes/CHA/C...
39,NYA200508230,NYA,2005,3315,https://www.baseball-reference.com/boxes/NYA/N...
40,ALS200507120,NLS,2005,3334,https://www.baseball-reference.com/boxes/ALS/A...
41,ALS200107100,ALS,2001,3360,https://www.baseball-reference.com/boxes/ALS/A...
42,ALS199707080,ALS,1997,3417,https://www.baseball-reference.com/boxes/ALS/A...
43,NLS199807070,ALS,1998,3454,https://www.baseball-reference.com/boxes/NLS/N...
44,ALS200507120,ALS,2005,3482,https://www.baseball-reference.com/boxes/ALS/A...
45,ALS199907130,NLS,1999,3537,https://www.baseball-reference.com/boxes/ALS/A...
46,ALS200307150,NLS,2003,3539,https://www.baseball-reference.com/boxes/ALS/A...
47,NLS200407130,NLS,2004,3659,https://www.baseball-reference.com/boxes/NLS/N...
48,ALS199907130,ALS,1999,3677,https://www.baseball-reference.com/boxes/ALS/A...
49,ALS200107100,NLS,2001,3935,https://www.baseball-reference.com/boxes/ALS/A...

In [12]:
top_hr['game_id'].apply(lambda g: bsu.create_bbref_boxscore_url(g)).apply(print)
None

https://www.baseball-reference.com/boxes/MIN/MIN200604160.shtml
https://www.baseball-reference.com/boxes/ANA/ANA200604070.shtml
https://www.baseball-reference.com/boxes/OAK/OAK200604050.shtml
https://www.baseball-reference.com/boxes/OAK/OAK200604040.shtml
https://www.baseball-reference.com/boxes/OAK/OAK200604030.shtml
https://www.baseball-reference.com/boxes/MIN/MIN200604140.shtml
https://www.baseball-reference.com/boxes/TEX/TEX200605050.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200604270.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200604290.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200609290.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200610050.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200610030.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200609270.shtml
https://www.baseball-reference.com/boxes/NYA/NYA201206080.shtml
https://www.baseball-reference.com/boxes/NYA/NYA201205020.shtml
https://www.baseball-reference.com/boxes/NLS/NLS200407130.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200506250.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200506150.shtml
https://www.baseball-reference.com/boxes/BAL/BAL200509290.shtml
https://www.baseball-reference.com/boxes/BAL/BAL200509280.shtml
https://www.baseball-reference.com/boxes/OAK/OAK200509020.shtml
https://www.baseball-reference.com/boxes/BOS/BOS200509300.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200506230.shtml
https://www.baseball-reference.com/boxes/TOR/TOR200509170.shtml
https://www.baseball-reference.com/boxes/KCA/KCA200506010.shtml
https://www.baseball-reference.com/boxes/TOR/TOR200509180.shtml
https://www.baseball-reference.com/boxes/TBA/TBA200509140.shtml
https://www.baseball-reference.com/boxes/TEX/TEX200507180.shtml
https://www.baseball-reference.com/boxes/NLS/NLS200207090.shtml
https://www.baseball-reference.com/boxes/CLE/CLE200508030.shtml
https://www.baseball-reference.com/boxes/ANA/ANA200507240.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200505250.shtml
https://www.baseball-reference.com/boxes/DET/DET200507010.shtml
https://www.baseball-reference.com/boxes/ANA/ANA200510050.shtml
https://www.baseball-reference.com/boxes/BOS/BOS200507170.shtml
https://www.baseball-reference.com/boxes/TBA/TBA200508170.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200507270.shtml
https://www.baseball-reference.com/boxes/CHA/CHA200508190.shtml
https://www.baseball-reference.com/boxes/CHA/CHA200508200.shtml
https://www.baseball-reference.com/boxes/NYA/NYA200508230.shtml
https://www.baseball-reference.com/boxes/ALS/ALS200507120.shtml
https://www.baseball-reference.com/boxes/ALS/ALS200107100.shtml
https://www.baseball-reference.com/boxes/ALS/ALS199707080.shtml
https://www.baseball-reference.com/boxes/NLS/NLS199807070.shtml
https://www.baseball-reference.com/boxes/ALS/ALS200507120.shtml
https://www.baseball-reference.com/boxes/ALS/ALS199907130.shtml
https://www.baseball-reference.com/boxes/ALS/ALS200307150.shtml
https://www.baseball-reference.com/boxes/NLS/NLS200407130.shtml
https://www.baseball-reference.com/boxes/ALS/ALS199907130.shtml
https://www.baseball-reference.com/boxes/ALS/ALS200107100.shtml

In [13]:
def get_lineups(game_id):
    df = gls_hr.query('game_id == @game_id').sort_values(['team', 'batting_pos'])
    df['name'] = bsu.get_player_names_col(df['player_id'], 'retro_id')
    return df[['team', 'batting_pos', 'name', 'hr']].rename(columns={'batting_pos': 'n'}).to_markdown(index=False)

print(get_lineups('ALS200107100'))

| team   |   n | name           |   hr |
|:-------|----:|:---------------|-----:|
| ALS    |   1 | Ichiro Suzuki  |  117 |
| ALS    |   2 | Alex Rodriguez |  696 |
| ALS    |   3 | Manny Ramirez  |  555 |
| ALS    |   4 | Bret Boone     |  252 |
| ALS    |   5 | Juan Gonzalez  |  434 |
| ALS    |   6 | John Olerud    |  255 |
| ALS    |   7 | Edgar Martinez |  309 |
| ALS    |   8 | Cal Ripken     |  431 |
| ALS    |   9 | Ivan Rodriguez |  311 |
| NLS    |   1 | Luis Gonzalez  |  354 |
| NLS    |   2 | Todd Helton    |  369 |
| NLS    |   3 | Barry Bonds    |  762 |
| NLS    |   4 | Sammy Sosa     |  609 |
| NLS    |   5 | Larry Walker   |  383 |
| NLS    |   6 | Mike Piazza    |  427 |
| NLS    |   7 | Chipper Jones  |  468 |
| NLS    |   8 | Jeff Kent      |  377 |
| NLS    |   9 | Rich Aurilia   |  186 |