In [1]:
import pandas as pd
import numpy as np
import boxball_loader as bbl

In [2]:
gl = bbl.load_gamelogs(bbl.GameType.RS, range(2012, 2021))
gl

,date,double_header,day_of_week,visiting_team,visiting_team_league,visiting_team_game_number,home_team,home_team_league,home_team_game_number,visitor_runs_scored,...,home_batting_8_name,home_batting_8_position,home_batting_9_player_id,home_batting_9_name,home_batting_9_position,additional_info,acquisition_info,game_id,yr,game_type
194936,2012-03-28,0,Wed,SEA,AL,1,OAK,AL,1,3,...,Brandon Allen,3.0,sogae001,Eric Sogard,5.0,None,Y,OAK201203280,2012,RS
194937,2012-03-29,0,Thu,SEA,AL,2,OAK,AL,2,1,...,Josh Donaldson,5.0,kaaik001,Kila Ka'aihue,3.0,None,Y,OAK201203290,2012,RS
194938,2012-04-04,0,Wed,SLN,NL,1,MIA,NL,1,4,...,John Buck,2.0,johnj009,Josh Johnson,1.0,None,Y,MIA201204040,2012,RS
194945,2012-04-05,0,Thu,LAN,NL,1,SDN,NL,1,5,...,Jason Bartlett,6.0,volqe001,Edinson Volquez,1.0,None,Y,SDN201204050,2012,RS
194944,2012-04-05,0,Thu,PHI,NL,1,PIT,NL,1,1,...,Clint Barmes,6.0,bedae001,Erik Bedard,1.0,None,Y,PIT201204050,2012,RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161558,2020-09-27,0,Sun,MIA,NL,60,NYA,AL,60,5,...,Gary Sanchez,2.0,wadet002,Tyler Wade,4.0,None,Y,NYA202009270,2020,RS
161560,2020-09-27,0,Sun,PHI,NL,60,TBA,AL,60,0,...,Michael Brosseau,4.0,perem005,Michael Perez,2.0,None,Y,TBA202009270,2020,RS
161562,2020-09-27,0,Sun,BAL,AL,60,TOR,AL,60,7,...,Jonathan Davis,9.0,jansd001,Danny Jansen,2.0,None,Y,TOR202009270,2020,RS
161561,2020-09-27,0,Sun,HOU,AL,60,TEX,AL,60,4,...,Ronald Guzman,3.0,tejea001,Anderson Tejeda,6.0,None,Y,TEX202009270,2020,RS
161556,2020-09-27,0,Sun,DET,AL,58,KCA,AL,60,1,...,Edward Olivares,8.0,lopen001,Nicky Lopez,4.0,None,Y,KCA202009270,2020,RS

In [3]:
weekday_types = pd.Series({'Sat': 'we', 'Sun': 'we', 'Fri': 'n', 'Wed': 'wd', 'Tue': 'wd', 'Mon': 'wd', 'Thu': 'wd'}).rename('weekday_type')
weekday_types.index.name='day_of_week'
weekday_types

day_of_week
Sat    we
Sun    we
Fri     n
Wed    wd
Tue    wd
Mon    wd
Thu    wd
Name: weekday_type, dtype: object

In [4]:
glw = pd.merge(left=gl, right=weekday_types, on='day_of_week')
glw

,date,double_header,day_of_week,visiting_team,visiting_team_league,visiting_team_game_number,home_team,home_team_league,home_team_game_number,visitor_runs_scored,...,home_batting_8_position,home_batting_9_player_id,home_batting_9_name,home_batting_9_position,additional_info,acquisition_info,game_id,yr,game_type,weekday_type
0,2012-03-28,0,Wed,SEA,AL,1,OAK,AL,1,3,...,3.0,sogae001,Eric Sogard,5.0,None,Y,OAK201203280,2012,RS,wd
1,2012-04-04,0,Wed,SLN,NL,1,MIA,NL,1,4,...,2.0,johnj009,Josh Johnson,1.0,None,Y,MIA201204040,2012,RS,wd
2,2012-04-11,0,Wed,PIT,NL,5,LAN,NL,6,1,...,2.0,billc001,Chad Billingsley,1.0,None,Y,LAN201204110,2012,RS,wd
3,2012-04-11,0,Wed,ATL,NL,6,HOU,NL,6,6,...,6.0,rodrw002,Wandy Rodriguez,1.0,None,Y,HOU201204110,2012,RS,wd
4,2012-04-11,0,Wed,SFN,NL,5,COL,NL,5,8,...,5.0,guthj001,Jeremy Guthrie,1.0,None,Y,COL201204110,2012,RS,wd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20331,2020-09-22,0,Tue,CHA,AL,55,CLE,AL,55,3,...,7.0,deshd002,Delino DeShields,8.0,None,Y,CLE202009220,2020,RS,wd
20332,2020-09-22,0,Tue,SLN,NL,52,KCA,AL,55,5,...,8.0,lopen001,Nicky Lopez,4.0,None,Y,KCA202009220,2020,RS,wd
20333,2020-09-22,0,Tue,DET,AL,53,MIN,AL,56,4,...,10.0,adrie001,Ehire Adrianza,6.0,None,Y,MIN202009220,2020,RS,wd
20334,2020-09-22,0,Tue,HOU,AL,55,SEA,AL,55,6,...,7.0,ervip001,Phillip Ervin,9.0,None,Y,SEA202009220,2020,RS,wd
20335,2020-09-22,0,Tue,NYA,AL,55,TOR,AL,55,12,...,2.0,davij007,Jonathan Davis,8.0,None,Y,TOR202009220,2020,RS,wd

In [5]:
att = glw.groupby(['home_team', 'weekday_type']).agg({'attendance': [np.mean, min, max, len]})
att

                          attendance
                                mean      min      max    len
home_team weekday_type
ANA       n             39978.105769  30112.0  44548.0  109.0
          wd            35785.770149  24304.0  45477.0  350.0
          we            38865.904306  17614.0  44742.0  219.0
ARI       n             28947.333333  19300.0  49130.0  111.0
          wd            21844.374622  12215.0  49043.0  345.0
...                              ...      ...      ...    ...
TOR       wd            27761.903904      0.0  48857.0  349.0
          we            37668.547619  16098.0  48154.0  218.0
WAS       n             32636.649485      0.0  42834.0  100.0
          wd            28415.692537      0.0  45274.0  351.0
          we            33952.495370      0.0  42662.0  227.0

[90 rows x 4 columns]

In [6]:
att_means = att['attendance']['mean'].unstack()
att_means

weekday_type             n            wd            we
home_team
ANA           39978.105769  35785.770149  38865.904306
ARI           28947.333333  21844.374622  31817.099057
ATL           34693.761905  24670.000000  34394.802885
BAL           29606.514851  20038.303030  31086.717593
BOS           36405.275510  35614.543284  36738.227907
CHA           22411.650485  18481.123494  25147.268868
CHN           36922.759615  35650.269231  38432.565217
CIN           30013.710000  21586.470238  31570.000000
CLE           26009.534653  16953.273810  23736.690476
COL           36923.714286  30739.628743  38433.856459
DET           32276.990196  28666.952239  33489.823810
HOU           29751.182692  24110.554217  31200.061321
KCA           28720.464646  22337.327381  26900.582160
LAN           47396.571429  44591.260479  47837.052381
MIA           18219.514286  17923.186186  21031.741627
MIL           34039.819048  29671.204204  37599.590476
MIN           28443.643564  26167.313609  30071.698565
NYA           42037.627451  39174.793413  42848.938679
NYN           31116.989899  26720.896450  32713.398104
OAK           22439.882353  17474.700297  25472.980861
PHI           29578.430000  28435.602985  33123.596244
PIT           29355.769231  21070.555556  30218.323810
SDN           30075.295238  23611.428144  33283.550239
SEA           28582.528846  20343.847305  30799.638095
SFN           40405.115385  39699.801802  40566.033175
SLN           43742.058824  40820.219219  44203.755869
TBA           17071.375000  13743.626506  20279.698113
TEX           35458.240385  29777.866071  36432.555024
TOR           31647.066667  27761.903904  37668.547619
WAS           32636.649485  28415.692537  33952.495370

In [9]:
# Ratio of weekday to weekend
(att_means['wd']/att_means['we']).sort_values()

home_team
BAL    0.644594
SEA    0.660522
TBA    0.677704
CIN    0.683765
OAK    0.686009
ARI    0.686561
PIT    0.697277
SDN    0.709402
CLE    0.714222
ATL    0.717260
CHA    0.734916
TOR    0.737005
HOU    0.772773
MIL    0.789136
COL    0.799806
NYN    0.816818
TEX    0.817342
KCA    0.830366
WAS    0.836925
MIA    0.852197
DET    0.855990
PHI    0.858470
MIN    0.870164
NYA    0.914254
ANA    0.920750
SLN    0.923456
CHN    0.927606
LAN    0.932149
BOS    0.969414
SFN    0.978646
dtype: float64